name: Release Automation

on:
  push:
    branches: [main]

jobs:
  release-please-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          # Commit to start releases from. This can be removed after the first release PR is merged.
          last-release-sha: 27283aff707ce928deb4440d80512fbdc1b04e83
          command: manifest
          monorepo-tags: true
          release-type: node
          package-name: polkadot-cloud
